# Server configuration
server:
  context-path: /micro
  port: 8080

# Spring properties
spring:
  application:
     name: inventory-microservice

  # MySQL Data source configuration
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://169.44.1.95/inventorydb
    username: dbuser
    password: Pass4dbUs3R
    port: 3306
    max-active: 4
    testOnBorrow: true
    validationQuery: SELECT 1

  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy

